GET http://127.0.0.1:8080/observer
Content-Type: application/json

###
POST http://127.0.0.1:8080/observer
Content-Type: application/json

{
  "licensePlate": "35BGP"
}

###
POST http://localhost:8080/observer
Content-Type: application/json

{
  "licensePlate": "35HLY"
}

###
POST http://localhost:8080/observer
Content-Type: application/json

{
  "licensePlate": "35BJU"
}

###
DELETE http://localhost:8080/observer/35BGP
Content-Type: application/json





